name: Test Datasets
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  run-dataset-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Clean up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
      - name: Install self
        working-directory: ${{github.workspace}}
        run: |
          # Since pylate makes problems otherwise:
          pip3 install pylate --no-deps
          pip3 install .[test,dev]
          pip3 cache purge
      - name: Run dataset tests
        working-directory: ${{github.workspace}}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: pytest --run-datasets --delete-cache tests/test_external_datasets.py
