name: Test Models
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  run-model-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install self
        working-directory: ${{github.workspace}}
        run: |
          # Since pylate makes problems otherwise:
          pip3 install pylate git+https://github.com/mjeensung/xtr-pytorch.git --no-deps
          pip3 install .[test,dev]
          pip3 cache purge
      - name: Run model tests
        working-directory: ${{github.workspace}}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: pytest --run-models --delete-cache tests/test_models
